services:
  api:
    build: ./api
    environment:
      AUDIT_HMAC: "change_me_in_prod"
      MODEL_CKPT: /app/models/minilm_cls_best
      RISK_RULES: /app/config/risk_rules.yaml
      EAGER_LOAD: "false"          # do not fail startup when model mount is empty
      STRICT_HEALTH: "false"       # health returns 200 with ok=false until model is valid
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./minilm_cls_best:/app/models/minilm_cls_best:ro
    expose:
      - "8000"
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8000/health"]
      interval: 10s
      timeout: 2s
      retries: 5

  ui:
    build:
      context: ./ui
      args:
        IS_LOCAL: ${IS_LOCAL:-false}  # Set via .env file or export IS_LOCAL=true for local dev
    ports:
      - "3000:80"
    volumes:
      - ./ui:/usr/share/nginx/html:ro   # live-mount your files
      - ./ui/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      api:
        condition: service_started
    restart: unless-stopped

  # optional: nginx reverse proxy + TLS (bring your certs or use Caddy)
